export const GET_TASK_REQUEST = "GET_TASK_REQUEST";
export const GET_PENDING_TASK_SUCCESS = "GET_PENDING_TASK_SUCCESS";
export const GET_DOING_TASK_SUCCESS = "GET_DOING_TASK_SUCCESS";
export const GET_DONE_TASK_SUCCESS = "GET_DONE_TASK_SUCCESS";
export const GET_TASK_FAILURE = "GET_TASK_FAILURE";
