export const GET_USER_DATA_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const POST_USER_DATA_REQUEST = "POST_USER_DATA_REQUEST";
export const POST_USER_DATA_SUCCESS = "POST_USER_DATA_SUCCESS";
export const POST_USER_DATA_FAILURE = "POST_USER_DATA_FAILURE";

export const PATCH_USER_DATA_REQUEST = "PATCH_USER_DATA_REQUEST";
export const PATCH_USER_DATA_SUCCESS = "PATCH_USER_DATA_SUCCESS";
export const PATCH_USER_DATA_FAILURE = "PATCH_USER_DATA_FAILURE";

export const DELETE_USER_DATA = "DELETE_USER_DATA";

export const FILTER_BY_STATE = "FILTER_BY_STATE";
export const FILTER_BY_YEAR = "FILTER_BY_YEAR";
export const SORT_BY_AGE = "SORT_BY_AGE";
