

export const GET_TODOS_REQUEST="GET_TODOS_REQUEST";
export const GET_TODOS_SUCESS="GET_TODOS_SUCESS";
export const GET_TODOS_FAILURE="GET_TODOS_FAILURE";

export const POST_TODOS_REQUEST="POST_TODOS_REQUEST";
export const POST_TODOS_SUCESS="POST_TODOS_SUCESS";
export const POST_TODOS_FAILURE="POST_TODOS_FAILURE";