export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCESS";
export const USER_LOGIN_FAILURE="USER_LOGIN_FAILURE";

// export const POST_TODOS_REQUEST="POST_TODOS_REQUEST";
// export const POST_TODOS_SUCESS="POST_TODOS_SUCESS";
// export const POST_TODOS_FAILURE="POST_TODOS_FAILURE";